<!DOCTYPE html>
<html lang="en">
<head>
        <title> DNS - Topic </title>
        <meta charset="UTF-8">
        <meta name="description" content="DNS Web Site - Topic">
        <meta name="keywords" content="DNS">
        <meta name="author" content="JohnVonNeumann">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="styles/style.css" rel="stylesheet">
</head>
<body>

	<header>
                <nav class="menu">
                        <ul>
                                <li class="menu-items">
                                        <a id="index-link" href="index.php"> Home </a>
                                </li>
                                <li class="menu-items">
                                        <a id="topic-link" href="topic.php"> Topic </a>
                                </li>
                                <li class="menu-items">
                                        <a id="enhancements" href="enhancements.html"> Enhancements </a>
                                </li>
                                <li class="menu-items">
                                        <a id="quiz" href="quiz.php"> Quiz </a>
                                </li>
                        </ul>
                </nav>
        </header>